name: what_when_where
description: What? When? Where?

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^2.2.0
  xml2json: ^3.0.3
  html: ^0.13.3+3
  flutter_staggered_grid_view: ^0.2.7
  rxdart: ^0.21.0
  url_launcher: ^5.0.1
  flutter_svg: ^0.11.0+1
  auto_size_text: ^1.0.0
  firebase_analytics: ^2.0.2+1
  firebase_crashlytics: ^0.0.4+2
  photo_view: ^0.5.0
  share: ^0.6.0+1
  path_provider: ^0.5.0+1
  audioplayer2: ^0.5.2
  transparent_image: ^0.1.0
  vibrate: ^0.0.4
  flutter_redux: ^0.5.3
  tuple: ^1.0.2
  quiver: ^2.0.1
  html_unescape: ^1.0.1+2
  shared_preferences: ^0.5.1+1
  dioc: ^0.1.4
  flutter_widget_from_html_core: ^0.1.3
  flutter_rating_bar: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family:  CustomIcons
      fonts:
        - asset: assets/CustomIcons.ttf
