name: what_when_where
description: What? When? Where?

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^0.14.2
  auto_size_text: ^2.1.0
  dio: ^3.0.9
  firebase_analytics: ^5.0.11
  firebase_crashlytics: ^0.1.3+3
  flutter_rating_bar: ^3.0.1+1
  flutter_redux: ^0.6.0
  flutter_staggered_grid_view: ^0.3.0
  flutter_svg: ^0.17.3+1
  flutter_vibrate: ^1.0.0
  flutter_widget_from_html_core: ^0.3.2+2
  freezed_annotation:
  get_it:
  html: ^0.14.0+3
  html_unescape: ^1.0.1+3
  injectable:
  json_serializable: ^3.3.0
  path_provider: ^1.6.5
  photo_view: ^0.9.2
  quiver: ^2.0.5
  rxdart: ^0.23.1
  share: ^0.6.3+6
  shared_preferences: ^0.5.6+3
  shimmer: ^1.1.0
  transparent_image: ^1.0.0
  url_launcher: ^5.4.2
  xml2json: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed:
  injectable_generator:
  mockito: ^4.1.1
  extra_pedantic: ^1.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family:  CustomIcons
      fonts:
        - asset: assets/CustomIcons.ttf
