name: what_when_where
description: What? When? Where?

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  dio: any
  xml2json: any
  html: any
  flutter_staggered_grid_view: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
