name: what_when_where
description: What? When? Where?

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: any
  xml2json: any
  html: any
  flutter_staggered_grid_view: any
  rxdart: any
  url_launcher: any
  flutter_svg: any
  auto_size_text: any
  firebase_analytics: any
  photo_view: any
  share: any
  path_provider: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
      - assets/
