name: what_when_where
description: What? When? Where?

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^2.0.0
  xml2json: ^3.0.3
  html: ^0.13.3+3
  flutter_staggered_grid_view: ^0.2.7
  rxdart: ^0.20.0
  url_launcher: ^5.0.1
  flutter_svg: ^0.10.3
  auto_size_text: ^0.3.0
  firebase_analytics: ^2.0.1
  photo_view: ^0.1.3
  share: ^0.6.0+1
  path_provider: ^0.5.0+1
  audioplayer: ^0.5.2
  transparent_image: ^0.1.0
  vibrate: ^0.0.4
  flutter_redux: ^0.5.3
  tuple: ^1.0.2
  quiver: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
      - assets/
