name: what_when_where
description: What? When? Where?

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  audioplayer2: ^0.5.2
  auto_size_text: ^1.1.2
  dio: ^3.0.4
  dioc: ^0.1.6
  firebase_analytics: ^5.0.2
  firebase_crashlytics: ^0.1.0+3
  flutter_rating_bar: ^1.3.0+1
  flutter_redux: ^0.5.4
  flutter_staggered_grid_view: ^0.3.0
  flutter_svg: ^0.14.4
  flutter_widget_from_html_core: ^0.1.5
  html: ^0.13.4
  html_unescape: ^1.0.1+3
  path_provider: ^1.2.0
  photo_view: ^0.5.0
  quiver: ^2.0.5
  rxdart: ^0.21.0
  share: ^0.6.3+1
  shared_preferences: ^0.5.4+3
  transparent_image: ^0.1.0
  tuple: ^1.0.3
  url_launcher: ^5.2.5
  vibrate: ^0.0.4
  xml2json: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family:  CustomIcons
      fonts:
        - asset: assets/CustomIcons.ttf
