name: what_when_where
description: What? When? Where?

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  audioplayer2: ^0.5.2
  auto_size_text: ^2.1.0
  dio: ^3.0.9
  dioc: ^0.1.6
  firebase_analytics: ^5.0.11
  firebase_crashlytics: ^0.1.3+3
  flutter_rating_bar: ^3.0.1+1
  flutter_redux: ^0.6.0
  flutter_staggered_grid_view: ^0.3.0
  flutter_svg: ^0.17.3+1
  flutter_widget_from_html_core: ^0.3.2+2
  html: ^0.14.0+3
  html_unescape: ^1.0.1+3
  path_provider: ^1.6.5
  provider: ^4.0.4
  photo_view: ^0.9.2
  quiver: ^2.0.5
  rxdart: ^0.23.1
  share: ^0.6.3+6
  shared_preferences: ^0.5.6+3
  transparent_image: ^1.0.0
  tuple: ^1.0.3
  url_launcher: ^5.4.2
  vibrate: ^0.0.4
  xml2json: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  extra_pedantic: ^1.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family:  CustomIcons
      fonts:
        - asset: assets/CustomIcons.ttf
